{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "strata.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "strata.fullname" . }}
  labels:
    {{- include "strata.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "strata.selectorLabels" . | nindent 6 }}
{{- end }}
